version: "3.8" # Specify the Docker Compose file format version

services:
  # FastAPI Application Service
  api:
    build: . # Build the image from the Dockerfile in the current directory
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    environment:
      # Database connection details for the API service
      # These refer to the 'db' service defined below
      DB_DRIVER_NAME: postgresql+asyncpg
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db # Refers to the 'db' service name within the Docker network
      DB_NAME: fastapi_db
      DB_PORT: 5432 # PostgreSQL's default internal port inside the container
      # Construct the DB_URL using the service name and internal port
      DB_URL: postgresql+asyncpg://postgres:password@db:5432/fastapi_db

      # Redis connection details for the API service
      # This refers to the 'redis' service defined below
      REDIS_URL: redis://redis:6379/0 # Refers to the 'redis' service name and default port

      # Other environment variables from your .env file
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      AlGORITHM: HS256
    depends_on:
      - db # Ensure the database service starts before the API
      - redis # Ensure the redis service starts before the API
    # Optional: If you have a .env file you want to load directly, you can use:
    # env_file:
    #   - .env

  # PostgreSQL Database Service
  db:
    image: postgres:13 # Use a specific version for stability, e.g., postgres:13
    environment:
      POSTGRES_DB: fastapi_db # Sets the default database name
      POSTGRES_USER: postgres # Sets the default user
      POSTGRES_PASSWORD: password # Sets the password for the default user
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data volume for PostgreSQL
    ports:
      - "5434:5432" # Map host port 5434 (from your .env) to container port 5432

  # Redis Cache Service
  redis:
    image: redis:latest # Use the latest Redis image
    ports:
      - "6380:6379" # Map host port 6379 to container port 6379
    volumes:
      - redis_data:/data # Persistent data volume for Redis (optional, but good for caching)

# Define named volumes for persistent data
volumes:
  postgres_data:
  redis_data:
