"""Initial migration

Revision ID: 2a47fb8adf3c
Revises: eb8cede36307
Create Date: 2025-07-07 21:49:19.354831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a47fb8adf3c'
down_revision: Union[str, Sequence[str], None] = 'eb8cede36307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_resource', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.drop_column('learning_resource', 'difficult')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_resource', sa.Column('difficult', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('learning_resource', 'difficulty')
    # ### end Alembic commands ###
