"""Initial migration

Revision ID: 36dd53a188d6
Revises: 57a7afac0631
Create Date: 2025-07-10 15:54:44.518061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dd53a188d6'
down_revision: Union[str, Sequence[str], None] = '57a7afac0631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skills', 'learning_resource', ['resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'resource_id')
    # ### end Alembic commands ###
