"""Initial migration

Revision ID: 37a3d8435827
Revises: a286a84da573
Create Date: 2025-07-09 21:54:58.671692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a3d8435827'
down_revision: Union[str, Sequence[str], None] = 'a286a84da573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_resource', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('learning_resource', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'learning_resource', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'learning_resource', 'user', ['user_id'], ['id'])
    op.add_column('skills', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skills', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'user_id')
    op.drop_constraint(None, 'learning_resource', type_='foreignkey')
    op.drop_constraint(None, 'learning_resource', type_='foreignkey')
    op.drop_column('learning_resource', 'skill_id')
    op.drop_column('learning_resource', 'user_id')
    # ### end Alembic commands ###
