"""Initial migration

Revision ID: 6504bb260bb0
Revises: c2d5bcea6888
Create Date: 2025-07-10 16:00:03.719823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6504bb260bb0'
down_revision: Union[str, Sequence[str], None] = 'c2d5bcea6888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resource_skill_association',
    sa.Column('learning_resource_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_resource_id'], ['learning_resource.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('learning_resource_id', 'skill_id')
    )
    op.drop_constraint(op.f('learning_resource_skill_id_fkey'), 'learning_resource', type_='foreignkey')
    op.drop_column('learning_resource', 'skill_id')
    op.drop_constraint(op.f('skills_resource_id_fkey'), 'skills', type_='foreignkey')
    op.drop_column('skills', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('skills_resource_id_fkey'), 'skills', 'learning_resource', ['resource_id'], ['id'])
    op.add_column('learning_resource', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('learning_resource_skill_id_fkey'), 'learning_resource', 'skills', ['skill_id'], ['id'])
    op.drop_table('learning_resource_skill_association')
    # ### end Alembic commands ###
