"""Initial migration

Revision ID: e7a76f33d447
Revises: 2a47fb8adf3c
Create Date: 2025-07-08 14:06:26.670901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7a76f33d447'
down_revision: Union[str, Sequence[str], None] = '2a47fb8adf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_resource', 'resource_type',
               existing_type=postgresql.ENUM('article', 'video', 'course', 'book', name='learningresourcetype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_resource', 'resource_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('article', 'video', 'course', 'book', name='learningresourcetype'),
               existing_nullable=False)
    # ### end Alembic commands ###
