"""Initial migration

Revision ID: eb8cede36307
Revises: 820bd9156fd3
Create Date: 2025-07-07 21:48:27.790855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8cede36307'
down_revision: Union[str, Sequence[str], None] = '820bd9156fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_resource', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_resource', 'url')
    # ### end Alembic commands ###
